# Generated by Django 6.0.2 on 2026-02-05 01:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('ecommerce_auth', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='apellido',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AddField(
            model_name='usuario',
            name='cedula_dorso',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='usuario',
            name='cedula_frente',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='usuario',
            name='descuento_mayorista',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Porcentaje de descuento para este mayorista', max_digits=5),
        ),
        migrations.AddField(
            model_name='usuario',
            name='estado_mayorista',
            field=models.CharField(blank=True, choices=[('PENDIENTE', 'Pendiente de Revisión'), ('EN_REVISION', 'En Revisión'), ('APROBADO', 'Aprobado'), ('RECHAZADO', 'Rechazado'), ('SUSPENDIDO', 'Suspendido')], default='PENDIENTE', max_length=20),
        ),
        migrations.AddField(
            model_name='usuario',
            name='fecha_revision',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='nit_empresa',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='usuario',
            name='nombre_empresa',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='usuario',
            name='notas_revision',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='usuario',
            name='numero_documento',
            field=models.CharField(blank=True, db_index=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='usuario',
            name='revisado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='revisiones_realizadas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='usuario',
            name='telefono',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='usuario',
            name='tipo',
            field=models.CharField(choices=[('STAFF', 'Staff Interno'), ('MAYORISTA', 'Mayorista')], default='STAFF', max_length=20),
        ),
        migrations.AddField(
            model_name='usuario',
            name='tipo_documento',
            field=models.CharField(blank=True, default='CC', max_length=20),
        ),
        migrations.AddIndex(
            model_name='usuario',
            index=models.Index(fields=['tipo', 'estado_mayorista'], name='auth_usuari_tipo_c2cde2_idx'),
        ),
        migrations.AddIndex(
            model_name='usuario',
            index=models.Index(fields=['numero_documento'], name='auth_usuari_numero__e70c42_idx'),
        ),
    ]
