# Generated by Django 6.0.2 on 2026-02-05 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce_auth', '0002_usuario_apellido_usuario_cedula_dorso_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='cedula_dorso',
            field=models.ImageField(blank=True, null=True, upload_to='cedulas/'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='cedula_frente',
            field=models.ImageField(blank=True, null=True, upload_to='cedulas/'),
        ),
    ]
