# Generated by Django 6.0.2 on 2026-02-06 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce_auth', '0003_change_cedula_to_imagefield'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='barrio',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='usuario',
            name='complemento',
            field=models.CharField(blank=True, default='', help_text='Apartamento, oficina, local, etc.', max_length=50),
        ),
        migrations.AddField(
            model_name='usuario',
            name='departamento',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='usuario',
            name='departamento_id',
            field=models.IntegerField(blank=True, help_text='ID del departamento en API Colombia', null=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='direccion',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='usuario',
            name='indicaciones_entrega',
            field=models.CharField(blank=True, default='', help_text='Indicaciones adicionales para entrega', max_length=128),
        ),
        migrations.AddField(
            model_name='usuario',
            name='latitud',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='longitud',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='municipio',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='usuario',
            name='municipio_id',
            field=models.IntegerField(blank=True, help_text='ID del municipio en API Colombia', null=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='tipo_domicilio',
            field=models.CharField(blank=True, choices=[('Residencial', 'Residencial'), ('Laboral', 'Laboral')], default='Residencial', max_length=20),
        ),
    ]
