# Generated by Django 6.0.2 on 2026-02-06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce_auth', '0004_add_direccion_mayorista'),
    ]

    operations = [
        migrations.CreateModel(
            name='DireccionMayorista',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('etiqueta', models.CharField(default='Mi dirección', max_length=50)),
                ('direccion', models.CharField(max_length=255)),
                ('complemento', models.CharField(blank=True, default='', help_text='Apartamento, oficina, local, etc.', max_length=100)),
                ('departamento', models.CharField(max_length=100)),
                ('departamento_id', models.IntegerField(blank=True, help_text='ID del departamento en API Colombia', null=True)),
                ('municipio', models.CharField(max_length=100)),
                ('municipio_id', models.IntegerField(blank=True, help_text='ID del municipio en API Colombia', null=True)),
                ('barrio', models.CharField(blank=True, default='', max_length=100)),
                ('indicaciones', models.CharField(blank=True, default='', help_text='Indicaciones para el repartidor', max_length=200)),
                ('tipo_domicilio', models.CharField(choices=[('Residencial', 'Residencial'), ('Laboral', 'Laboral')], default='Residencial', max_length=20)),
                ('nombre_contacto', models.CharField(blank=True, default='', max_length=100)),
                ('telefono', models.CharField(max_length=20)),
                ('latitud', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('longitud', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('is_default', models.BooleanField(default=False, help_text='¿Es la dirección principal?')),
                ('activa', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='direcciones', to='ecommerce_auth.usuario')),
            ],
            options={
                'verbose_name': 'Dirección de Mayorista',
                'verbose_name_plural': 'Direcciones de Mayoristas',
                'db_table': 'auth_direcciones_mayorista',
                'ordering': ['-is_default', '-fecha_creacion'],
            },
        ),
    ]
