# Generated by Django 6.0.1 on 2026-02-07 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce_auth', '0005_create_direccion_mayorista'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='reset_code',
            field=models.CharField(blank=True, help_text='Código de 6 dígitos para recuperación', max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='reset_code_expires',
            field=models.DateTimeField(blank=True, help_text='Expiración del código de recuperación', null=True),
        ),
    ]
