# Generated by Django 6.0.1 on 2026-01-17 05:28

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce_persistence', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductoModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('codigo', models.CharField(db_index=True, max_length=50, unique=True)),
                ('nombre', models.CharField(max_length=200)),
                ('descripcion', models.TextField()),
                ('moneda_precio', models.CharField(max_length=3)),
                ('monto_precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stock_actual', models.IntegerField(default=0)),
                ('stock_minimo', models.IntegerField(default=0)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
                'db_table': 'productos',
                'ordering': ['-fecha_creacion'],
                'indexes': [models.Index(fields=['codigo'], name='productos_codigo_1fb639_idx'), models.Index(fields=['nombre'], name='productos_nombre_d31432_idx'), models.Index(fields=['activo', 'stock_actual'], name='productos_activo_b638e0_idx')],
            },
        ),
    ]
