# Generated by Django 6.0.1 on 2026-01-17 05:32

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce_persistence', '0002_productomodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrdenModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('estado', models.CharField(max_length=20)),
                ('total_monto', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_moneda', models.CharField(default='USD', max_length=3)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ordenes', to='ecommerce_persistence.clientemodel')),
            ],
            options={
                'verbose_name': 'Orden',
                'verbose_name_plural': 'Ordenes',
                'db_table': 'ordenes',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='LineaOrdenModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('cantidad', models.IntegerField()),
                ('precio_unitario_monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('precio_unitario_moneda', models.CharField(max_length=3)),
                ('subtotal_monto', models.DecimalField(decimal_places=2, max_digits=12)),
                ('subtotal_moneda', models.CharField(max_length=3)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lineas_orden', to='ecommerce_persistence.productomodel')),
                ('orden', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lineas', to='ecommerce_persistence.ordenmodel')),
            ],
            options={
                'verbose_name': 'Línea de Orden',
                'verbose_name_plural': 'Líneas de Orden',
                'db_table': 'lineas_orden',
                'ordering': ['orden', 'producto'],
            },
        ),
        migrations.AddIndex(
            model_name='ordenmodel',
            index=models.Index(fields=['cliente'], name='ordenes_cliente_463be0_idx'),
        ),
        migrations.AddIndex(
            model_name='ordenmodel',
            index=models.Index(fields=['estado'], name='ordenes_estado_c58784_idx'),
        ),
        migrations.AddIndex(
            model_name='ordenmodel',
            index=models.Index(fields=['fecha_creacion'], name='ordenes_fecha_c_7b8fbe_idx'),
        ),
    ]
