# Generated by Django 6.0.1 on 2026-01-18 01:56

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce_persistence', '0005_auditoriaaccesoapi'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarritoModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('usuario_id', models.UUIDField(db_index=True)),
                ('estado', models.CharField(choices=[('CREADO', 'Creado'), ('ACTIVO', 'Activo'), ('BLOQUEADO', 'Bloqueado'), ('CONFIRMADO', 'Confirmado'), ('EXPIRADO', 'Expirado')], db_index=True, default='CREADO', max_length=20)),
                ('version', models.IntegerField(default=1)),
                ('total_bruto_monto', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('total_bruto_moneda', models.CharField(default='USD', max_length=3)),
                ('total_descuentos_monto', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('total_descuentos_moneda', models.CharField(default='USD', max_length=3)),
                ('total_final_monto', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('total_final_moneda', models.CharField(default='USD', max_length=3)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('fecha_expiracion', models.DateTimeField(blank=True, null=True)),
                ('fecha_bloqueo', models.DateTimeField(blank=True, null=True)),
                ('fecha_confirmacion', models.DateTimeField(blank=True, null=True)),
                ('motivo_bloqueo', models.CharField(blank=True, max_length=100, null=True)),
                ('motivo_expiracion', models.CharField(blank=True, max_length=100, null=True)),
                ('orden_generada_id', models.UUIDField(blank=True, null=True, unique=True)),
            ],
            options={
                'verbose_name': 'Carrito',
                'verbose_name_plural': 'Carritos',
                'db_table': 'carritos',
                'ordering': ['-fecha_modificacion'],
            },
        ),
        migrations.CreateModel(
            name='ImagenProductoModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('url', models.URLField(max_length=500)),
                ('es_principal', models.BooleanField(default=False)),
                ('orden', models.IntegerField(default=0)),
                ('alt_text', models.CharField(blank=True, max_length=200)),
            ],
            options={
                'db_table': 'imagenes_producto',
                'ordering': ['orden'],
            },
        ),
        migrations.CreateModel(
            name='ItemCarritoModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('producto_id', models.UUIDField(db_index=True)),
                ('sku_snapshot', models.CharField(max_length=50)),
                ('nombre_snapshot', models.CharField(max_length=200)),
                ('precio_unitario_monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('precio_unitario_moneda', models.CharField(default='USD', max_length=3)),
                ('cantidad', models.PositiveIntegerField(default=1)),
                ('subtotal_monto', models.DecimalField(decimal_places=2, max_digits=12)),
                ('subtotal_moneda', models.CharField(default='USD', max_length=3)),
                ('fecha_agregado', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Item de Carrito',
                'verbose_name_plural': 'Items de Carrito',
                'db_table': 'items_carrito',
                'ordering': ['fecha_agregado'],
            },
        ),
        migrations.AddField(
            model_name='productomodel',
            name='calidad',
            field=models.CharField(blank=True, choices=[('remy', 'Remy'), ('virgin', 'Virgin'), ('double_drawn', 'Double Drawn'), ('single_drawn', 'Single Drawn'), ('raw', 'Raw')], db_index=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='productomodel',
            name='color',
            field=models.CharField(blank=True, choices=[('negro_natural', 'Negro Natural'), ('negro_azabache', 'Negro Azabache'), ('castano_oscuro', 'Castaño Oscuro'), ('castano_medio', 'Castaño Medio'), ('castano_claro', 'Castaño Claro'), ('castano_chocolate', 'Castaño Chocolate'), ('rubio_oscuro', 'Rubio Oscuro'), ('rubio_medio', 'Rubio Medio'), ('rubio_claro', 'Rubio Claro'), ('rubio_platino', 'Rubio Platino'), ('rubio_cenizo', 'Rubio Cenizo'), ('rubio_miel', 'Rubio Miel'), ('pelirrojo', 'Pelirrojo'), ('cobrizo', 'Cobrizo'), ('borgona', 'Borgoña'), ('rosa', 'Rosa'), ('azul', 'Azul'), ('morado', 'Morado'), ('verde', 'Verde'), ('gris', 'Gris'), ('ombre', 'Ombré'), ('balayage', 'Balayage'), ('highlights', 'Highlights')], db_index=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='productomodel',
            name='descripcion_corta',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='productomodel',
            name='destacado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='productomodel',
            name='es_nuevo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='productomodel',
            name='imagen_principal',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='productomodel',
            name='largo',
            field=models.CharField(blank=True, choices=[('8', '8 pulgadas'), ('10', '10 pulgadas'), ('12', '12 pulgadas'), ('14', '14 pulgadas'), ('16', '16 pulgadas'), ('18', '18 pulgadas'), ('20', '20 pulgadas'), ('22', '22 pulgadas'), ('24', '24 pulgadas'), ('26', '26 pulgadas'), ('28', '28 pulgadas'), ('30', '30 pulgadas'), ('32', '32 pulgadas')], db_index=True, max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='productomodel',
            name='metodo',
            field=models.CharField(blank=True, choices=[('clip_in', 'Clip-In'), ('tape_in', 'Tape-In'), ('keratin_bond', 'Keratin Bond'), ('micro_link', 'Micro Link'), ('sew_in', 'Sew-In'), ('fusion', 'Fusión'), ('halo', 'Halo'), ('ponytail', 'Ponytail'), ('bundle', 'Bundle'), ('closure', 'Closure'), ('frontal', 'Frontal'), ('wig', 'Peluca')], db_index=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='productomodel',
            name='monto_precio_original',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='productomodel',
            name='origen',
            field=models.CharField(blank=True, choices=[('brasileno', 'Brasileño'), ('peruano', 'Peruano'), ('indio', 'Indio'), ('malayo', 'Malayo'), ('camboyano', 'Camboyano'), ('mongol', 'Mongol'), ('europeo', 'Europeo'), ('vietnamita', 'Vietnamita'), ('chino', 'Chino'), ('ruso', 'Ruso')], db_index=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='productomodel',
            name='peso_gramos',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='productomodel',
            name='tipo',
            field=models.CharField(blank=True, choices=[('liso', 'Liso'), ('ondulado', 'Ondulado'), ('rizado', 'Rizado'), ('afro', 'Afro'), ('kinky', 'Kinky'), ('body_wave', 'Body Wave'), ('deep_wave', 'Deep Wave'), ('water_wave', 'Water Wave'), ('loose_wave', 'Loose Wave')], db_index=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='productomodel',
            name='total_valoraciones',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='productomodel',
            name='total_vendidos',
            field=models.IntegerField(db_index=True, default=0),
        ),
        migrations.AddField(
            model_name='productomodel',
            name='valoracion_promedio',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=3),
        ),
        migrations.AlterField(
            model_name='productomodel',
            name='moneda_precio',
            field=models.CharField(default='USD', max_length=3),
        ),
        migrations.AddIndex(
            model_name='productomodel',
            index=models.Index(fields=['color', 'activo'], name='productos_color_7aa3fe_idx'),
        ),
        migrations.AddIndex(
            model_name='productomodel',
            index=models.Index(fields=['tipo', 'activo'], name='productos_tipo_1bcab9_idx'),
        ),
        migrations.AddIndex(
            model_name='productomodel',
            index=models.Index(fields=['largo', 'activo'], name='productos_largo_82baf0_idx'),
        ),
        migrations.AddIndex(
            model_name='productomodel',
            index=models.Index(fields=['origen', 'activo'], name='productos_origen_4d3a67_idx'),
        ),
        migrations.AddIndex(
            model_name='productomodel',
            index=models.Index(fields=['metodo', 'activo'], name='productos_metodo_be103d_idx'),
        ),
        migrations.AddIndex(
            model_name='productomodel',
            index=models.Index(fields=['calidad', 'activo'], name='productos_calidad_758aa4_idx'),
        ),
        migrations.AddIndex(
            model_name='productomodel',
            index=models.Index(fields=['monto_precio', 'activo'], name='productos_monto_p_6d02b6_idx'),
        ),
        migrations.AddIndex(
            model_name='productomodel',
            index=models.Index(fields=['activo', 'stock_actual', '-total_vendidos'], name='productos_activo_75cd59_idx'),
        ),
        migrations.AddIndex(
            model_name='productomodel',
            index=models.Index(fields=['activo', 'color', 'tipo'], name='productos_activo_efa865_idx'),
        ),
        migrations.AddIndex(
            model_name='carritomodel',
            index=models.Index(fields=['usuario_id', 'estado'], name='carritos_usuario_12dc42_idx'),
        ),
        migrations.AddIndex(
            model_name='carritomodel',
            index=models.Index(fields=['estado', '-fecha_modificacion'], name='carritos_estado_2e1404_idx'),
        ),
        migrations.AddIndex(
            model_name='carritomodel',
            index=models.Index(fields=['fecha_expiracion', 'estado'], name='carritos_fecha_e_f891ff_idx'),
        ),
        migrations.AddConstraint(
            model_name='carritomodel',
            constraint=models.UniqueConstraint(condition=models.Q(('estado__in', ['CREADO', 'ACTIVO', 'BLOQUEADO'])), fields=('usuario_id',), name='unique_carrito_activo_por_usuario'),
        ),
        migrations.AddField(
            model_name='imagenproductomodel',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagenes', to='ecommerce_persistence.productomodel'),
        ),
        migrations.AddField(
            model_name='itemcarritomodel',
            name='carrito',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='ecommerce_persistence.carritomodel'),
        ),
        migrations.AddConstraint(
            model_name='itemcarritomodel',
            constraint=models.UniqueConstraint(fields=('carrito', 'producto_id'), name='unique_producto_por_carrito'),
        ),
    ]
