# Generated by Django 6.0.1 on 2026-01-18 12:11

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce_persistence', '0006_carritomodel_imagenproductomodel_itemcarritomodel_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FavoritoModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('usuario_id', models.UUIDField(db_index=True)),
                ('fecha_agregado', models.DateTimeField(auto_now_add=True)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favoritos', to='ecommerce_persistence.productomodel')),
            ],
            options={
                'verbose_name': 'Favorito',
                'verbose_name_plural': 'Favoritos',
                'db_table': 'favoritos',
                'ordering': ['-fecha_agregado'],
                'constraints': [models.UniqueConstraint(fields=('usuario_id', 'producto'), name='unique_favorito_por_usuario')],
            },
        ),
    ]
