# Generated by Django 6.0.1 on 2026-01-20 14:27

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce_persistence', '0007_favoritomodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('descripcion', models.TextField(blank=True)),
                ('descripcion_corta', models.CharField(blank=True, help_text='Texto corto para mostrar en tarjetas', max_length=150)),
                ('imagen', models.URLField(blank=True, max_length=500, null=True)),
                ('prioridad', models.IntegerField(choices=[(1, 'Prioridad Alta (Grande)'), (2, 'Prioridad Media'), (3, 'Prioridad Baja')], default=2)),
                ('orden', models.IntegerField(default=0)),
                ('activo', models.BooleanField(default=True)),
                ('mostrar_en_home', models.BooleanField(default=True, help_text='Mostrar en página principal')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Categoría',
                'verbose_name_plural': 'Categorías',
                'db_table': 'categorias',
                'ordering': ['prioridad', 'orden', 'nombre'],
                'indexes': [models.Index(fields=['slug'], name='categorias_slug_e69df5_idx'), models.Index(fields=['activo', 'prioridad'], name='categorias_activo_5958a4_idx'), models.Index(fields=['activo', 'mostrar_en_home', 'prioridad'], name='categorias_activo_068a5a_idx')],
            },
        ),
    ]
