# Generated by Django 6.0.1 on 2026-02-01 00:00

import uuid
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce_persistence', '0007_favoritomodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductoVarianteModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sku', models.CharField(db_index=True, max_length=80, unique=True)),
                ('color', models.CharField(blank=True, choices=[('negro_natural', 'Negro Natural'), ('negro_azabache', 'Negro Azabache'), ('castano_oscuro', 'Castaño Oscuro'), ('castano_medio', 'Castaño Medio'), ('castano_claro', 'Castaño Claro'), ('castano_chocolate', 'Castaño Chocolate'), ('rubio_oscuro', 'Rubio Oscuro'), ('rubio_medio', 'Rubio Medio'), ('rubio_claro', 'Rubio Claro'), ('rubio_platino', 'Rubio Platino'), ('rubio_cenizo', 'Rubio Cenizo'), ('rubio_miel', 'Rubio Miel'), ('pelirrojo', 'Pelirrojo'), ('cobrizo', 'Cobrizo'), ('borgona', 'Borgoña'), ('rosa', 'Rosa'), ('azul', 'Azul'), ('morado', 'Morado'), ('verde', 'Verde'), ('gris', 'Gris'), ('ombre', 'Ombré'), ('balayage', 'Balayage'), ('highlights', 'Highlights')], db_index=True, max_length=50, null=True)),
                ('largo', models.CharField(blank=True, choices=[('8', '8 pulgadas'), ('10', '10 pulgadas'), ('12', '12 pulgadas'), ('14', '14 pulgadas'), ('16', '16 pulgadas'), ('18', '18 pulgadas'), ('20', '20 pulgadas'), ('22', '22 pulgadas'), ('24', '24 pulgadas'), ('26', '26 pulgadas'), ('28', '28 pulgadas'), ('30', '30 pulgadas'), ('32', '32 pulgadas')], db_index=True, max_length=50, null=True)),
                ('precio_monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('precio_moneda', models.CharField(default='COP', max_length=3)),
                ('stock_actual', models.IntegerField(default=0)),
                ('stock_minimo', models.IntegerField(default=0)),
                ('imagen_url', models.URLField(blank=True, max_length=500, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('orden', models.IntegerField(default=0)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variantes', to='ecommerce_persistence.productomodel')),
            ],
            options={
                'verbose_name': 'Variante de Producto',
                'verbose_name_plural': 'Variantes de Producto',
                'db_table': 'productos_variantes',
                'ordering': ['orden', '-fecha_creacion'],
                'indexes': [
                    models.Index(fields=['producto', 'activo'], name='productos_var_producto_4f2d5c_idx'),
                    models.Index(fields=['producto', 'color'], name='productos_var_producto_6d4bc6_idx'),
                    models.Index(fields=['producto', 'largo'], name='productos_var_producto_1b6c50_idx'),
                    models.Index(fields=['activo', 'stock_actual'], name='productos_var_activo_77e0b3_idx'),
                ],
            },
        ),
        migrations.AddField(
            model_name='itemcarritomodel',
            name='variante_id',
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='itemcarritomodel',
            name='variante_sku',
            field=models.CharField(blank=True, default='', max_length=80),
        ),
        migrations.AddField(
            model_name='itemcarritomodel',
            name='color_snapshot',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='itemcarritomodel',
            name='largo_snapshot',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.RemoveConstraint(
            model_name='itemcarritomodel',
            name='unique_producto_por_carrito',
        ),
        migrations.AddConstraint(
            model_name='itemcarritomodel',
            constraint=models.UniqueConstraint(fields=('carrito', 'variante_id'), name='unique_variante_por_carrito'),
        ),
        migrations.AddField(
            model_name='lineaordenmodel',
            name='variante_id',
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='lineaordenmodel',
            name='variante_sku',
            field=models.CharField(blank=True, default='', max_length=80),
        ),
        migrations.AddField(
            model_name='lineaordenmodel',
            name='color_snapshot',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='lineaordenmodel',
            name='largo_snapshot',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddConstraint(
            model_name='productovariantemodel',
            constraint=models.UniqueConstraint(fields=('producto', 'color', 'largo'), name='unique_variante_por_color_largo'),
        ),
    ]
