# Generated by Django 6.0.1 on 2026-01-20 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce_persistence', '0008_categoriamodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoriamodel',
            name='imagen',
            field=models.URLField(blank=True, max_length=2000, null=True),
        ),
    ]
