# Generated by Django 6.0.1 on 2026-01-20 15:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce_persistence', '0009_aumentar_longitud_url_categoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='productomodel',
            name='categoria',
            field=models.ForeignKey(blank=True, help_text='Categoría a la que pertenece este producto', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='productos', to='ecommerce_persistence.categoriamodel'),
        ),
    ]
