# Generated by Django 6.0.1 on 2026-01-24 15:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce_persistence', '0011_aumentar_longitud_atributos_productos'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientemodel',
            name='barrio',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='clientemodel',
            name='departamento',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='clientemodel',
            name='direccion',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='clientemodel',
            name='municipio',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='ordenmodel',
            name='barrio',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='ordenmodel',
            name='codigo',
            field=models.CharField(db_index=True, default='', max_length=20, unique=True),
        ),
        migrations.AddField(
            model_name='ordenmodel',
            name='departamento',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='ordenmodel',
            name='direccion_envio',
            field=models.CharField(default='', max_length=300),
        ),
        migrations.AddField(
            model_name='ordenmodel',
            name='envio_monto',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='ordenmodel',
            name='metodo_pago',
            field=models.CharField(choices=[('epayco', 'ePayco'), ('whatsapp', 'WhatsApp/Asesor'), ('transferencia', 'Transferencia'), ('contraentrega', 'Contra Entrega')], default='whatsapp', max_length=20),
        ),
        migrations.AddField(
            model_name='ordenmodel',
            name='municipio',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='ordenmodel',
            name='notas_envio',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='ordenmodel',
            name='subtotal_monto',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='ordenmodel',
            name='cliente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ordenes', to='ecommerce_persistence.clientemodel'),
        ),
        migrations.AlterField(
            model_name='ordenmodel',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('confirmada', 'Confirmada'), ('en_proceso', 'En Proceso'), ('enviada', 'Enviada'), ('completada', 'Completada'), ('cancelada', 'Cancelada')], default='pendiente', max_length=20),
        ),
        migrations.AlterField(
            model_name='ordenmodel',
            name='total_moneda',
            field=models.CharField(default='COP', max_length=3),
        ),
        migrations.AlterField(
            model_name='productomodel',
            name='calidad',
            field=models.CharField(blank=True, choices=[('remy', 'Remy'), ('virgin', 'Virgin'), ('double_drawn', 'Double Drawn'), ('single_drawn', 'Single Drawn'), ('raw', 'Raw')], db_index=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='productomodel',
            name='color',
            field=models.CharField(blank=True, choices=[('negro_natural', 'Negro Natural'), ('negro_azabache', 'Negro Azabache'), ('castano_oscuro', 'Castaño Oscuro'), ('castano_medio', 'Castaño Medio'), ('castano_claro', 'Castaño Claro'), ('castano_chocolate', 'Castaño Chocolate'), ('rubio_oscuro', 'Rubio Oscuro'), ('rubio_medio', 'Rubio Medio'), ('rubio_claro', 'Rubio Claro'), ('rubio_platino', 'Rubio Platino'), ('rubio_cenizo', 'Rubio Cenizo'), ('rubio_miel', 'Rubio Miel'), ('pelirrojo', 'Pelirrojo'), ('cobrizo', 'Cobrizo'), ('borgona', 'Borgoña'), ('rosa', 'Rosa'), ('azul', 'Azul'), ('morado', 'Morado'), ('verde', 'Verde'), ('gris', 'Gris'), ('ombre', 'Ombré'), ('balayage', 'Balayage'), ('highlights', 'Highlights')], db_index=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='productomodel',
            name='largo',
            field=models.CharField(blank=True, choices=[('8', '8 pulgadas'), ('10', '10 pulgadas'), ('12', '12 pulgadas'), ('14', '14 pulgadas'), ('16', '16 pulgadas'), ('18', '18 pulgadas'), ('20', '20 pulgadas'), ('22', '22 pulgadas'), ('24', '24 pulgadas'), ('26', '26 pulgadas'), ('28', '28 pulgadas'), ('30', '30 pulgadas'), ('32', '32 pulgadas')], db_index=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='productomodel',
            name='metodo',
            field=models.CharField(blank=True, choices=[('clip_in', 'Clip-In'), ('tape_in', 'Tape-In'), ('keratin_bond', 'Keratin Bond'), ('micro_link', 'Micro Link'), ('sew_in', 'Sew-In'), ('fusion', 'Fusión'), ('halo', 'Halo'), ('ponytail', 'Ponytail'), ('bundle', 'Bundle'), ('closure', 'Closure'), ('frontal', 'Frontal'), ('wig', 'Peluca')], db_index=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='productomodel',
            name='origen',
            field=models.CharField(blank=True, choices=[('brasileno', 'Brasileño'), ('peruano', 'Peruano'), ('indio', 'Indio'), ('malayo', 'Malayo'), ('camboyano', 'Camboyano'), ('mongol', 'Mongol'), ('europeo', 'Europeo'), ('vietnamita', 'Vietnamita'), ('chino', 'Chino'), ('ruso', 'Ruso')], db_index=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='productomodel',
            name='tipo',
            field=models.CharField(blank=True, choices=[('liso', 'Liso'), ('ondulado', 'Ondulado'), ('rizado', 'Rizado'), ('afro', 'Afro'), ('kinky', 'Kinky'), ('body_wave', 'Body Wave'), ('deep_wave', 'Deep Wave'), ('water_wave', 'Water Wave'), ('loose_wave', 'Loose Wave')], db_index=True, max_length=50, null=True),
        ),
        migrations.AddIndex(
            model_name='ordenmodel',
            index=models.Index(fields=['codigo'], name='ordenes_codigo_8383b6_idx'),
        ),
    ]
