# Generated by Django 6.0.1 on 2026-01-26 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce_persistence', '0012_add_direccion_cliente'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordenmodel',
            name='reserva_expira_en',
            field=models.DateTimeField(blank=True, help_text='Fecha de expiracion de la reserva de stock (solo para ordenes pendientes)', null=True),
        ),
        migrations.AddField(
            model_name='productomodel',
            name='stock_reservado',
            field=models.IntegerField(default=0, help_text='Stock temporalmente reservado por ordenes pendientes'),
        ),
    ]
