# Generated by Django 6.0.1 on 2026-01-31 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce_persistence', '0014_agregar_email_threading'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordenmodel',
            name='reserva_expira_en',
        ),
        migrations.AddIndex(
            model_name='lineaordenmodel',
            index=models.Index(fields=['orden', 'producto'], name='lineas_orde_orden_i_bca61c_idx'),
        ),
        migrations.AddIndex(
            model_name='lineaordenmodel',
            index=models.Index(fields=['orden_id'], name='lineas_orde_orden_i_c33793_idx'),
        ),
        migrations.AddIndex(
            model_name='ordenmodel',
            index=models.Index(fields=['estado', '-fecha_creacion'], name='ordenes_estado_9f69da_idx'),
        ),
        migrations.AddIndex(
            model_name='ordenmodel',
            index=models.Index(fields=['activo', '-fecha_creacion'], name='ordenes_activo_9a3469_idx'),
        ),
        migrations.AddIndex(
            model_name='ordenmodel',
            index=models.Index(fields=['cliente', '-fecha_creacion'], name='ordenes_cliente_c0469f_idx'),
        ),
        migrations.AddIndex(
            model_name='ordenmodel',
            index=models.Index(fields=['-fecha_creacion', 'estado'], name='ordenes_fecha_c_044982_idx'),
        ),
    ]
