# Generated by Django 6.0.2 on 2026-02-07 01:13

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce_persistence', '0015_optimizar_indices_ordenes'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductoVistoModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('usuario_id', models.UUIDField(db_index=True)),
                ('email', models.EmailField(blank=True, db_index=True, max_length=254, null=True)),
                ('fecha_visto', models.DateTimeField(auto_now=True)),
                ('veces_visto', models.PositiveIntegerField(default=1)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vistos', to='ecommerce_persistence.productomodel')),
            ],
            options={
                'verbose_name': 'Producto Visto',
                'verbose_name_plural': 'Productos Vistos',
                'db_table': 'productos_vistos',
                'ordering': ['-fecha_visto'],
                'indexes': [models.Index(fields=['usuario_id', '-fecha_visto'], name='productos_v_usuario_a6eb8a_idx'), models.Index(fields=['email', '-fecha_visto'], name='productos_v_email_632a43_idx')],
                'constraints': [models.UniqueConstraint(fields=('usuario_id', 'producto'), name='unique_visto_por_usuario')],
            },
        ),
    ]
