# Generated by Django 6.0.1 on 2026-02-07 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce_persistence', '0016_productovistomodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='productomodel',
            name='cantidad_minima_mayorista',
            field=models.IntegerField(default=1, help_text='Cantidad mínima para venta mayorista'),
        ),
    ]
