# Generated by Django 6.0.1 on 2026-02-09

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce_persistence', '0017_productomodel_cantidad_minima_mayorista'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificacionModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('usuario_id', models.UUIDField(db_index=True)),
                ('email', models.EmailField(db_index=True, max_length=254)),
                ('tipo', models.CharField(choices=[('orden_estado', 'Estado de Orden'), ('password_changed', 'Cambio de Contrasena'), ('account_status', 'Estado de Cuenta'), ('promo_stock', 'Promos y Stock'), ('sistema', 'Sistema')], db_index=True, default='sistema', max_length=30)),
                ('titulo', models.CharField(max_length=200)),
                ('mensaje', models.TextField()),
                ('data', models.JSONField(blank=True, default=dict)),
                ('leida', models.BooleanField(db_index=True, default=False)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('fecha_leida', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'notificaciones',
                'verbose_name': 'Notificacion',
                'verbose_name_plural': 'Notificaciones',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.AddIndex(
            model_name='notificacionmodel',
            index=models.Index(fields=['usuario_id', '-fecha_creacion'], name='notificacio_usuario__2a4eb6_idx'),
        ),
        migrations.AddIndex(
            model_name='notificacionmodel',
            index=models.Index(fields=['email', '-fecha_creacion'], name='notificacio_email_78d0f0_idx'),
        ),
        migrations.AddIndex(
            model_name='notificacionmodel',
            index=models.Index(fields=['leida', '-fecha_creacion'], name='notificacio_leida_81adf1_idx'),
        ),
    ]
