# Generated by Django 6.0.1 on 2026-02-13 14:57

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce_persistence', '0019_productomodel_b2b_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResenaProductoModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('rating', models.PositiveSmallIntegerField()),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('aprobada', 'Aprobada'), ('rechazada', 'Rechazada')], db_index=True, default='pendiente', max_length=20)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Reseña de producto',
                'verbose_name_plural': 'Reseñas de producto',
                'db_table': 'resenas_producto',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.AddField(
            model_name='resenaproductomodel',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resenas', to='ecommerce_persistence.clientemodel'),
        ),
        migrations.AddField(
            model_name='resenaproductomodel',
            name='orden',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resenas', to='ecommerce_persistence.ordenmodel'),
        ),
        migrations.AddField(
            model_name='resenaproductomodel',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resenas', to='ecommerce_persistence.productomodel'),
        ),
        migrations.AddIndex(
            model_name='resenaproductomodel',
            index=models.Index(fields=['producto', 'estado'], name='resenas_pro_product_10fc4d_idx'),
        ),
        migrations.AddIndex(
            model_name='resenaproductomodel',
            index=models.Index(fields=['cliente', 'producto'], name='resenas_pro_cliente_135c0d_idx'),
        ),
        migrations.AddIndex(
            model_name='resenaproductomodel',
            index=models.Index(fields=['-fecha_creacion', 'estado'], name='resenas_pro_fecha_c_691008_idx'),
        ),
        migrations.AddConstraint(
            model_name='resenaproductomodel',
            constraint=models.UniqueConstraint(fields=('producto', 'cliente'), name='unique_resena_por_cliente_producto'),
        ),
    ]
