# Generated by Django 6.0.1 on 2026-02-13 19:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce_persistence', '0008_productovariantemodel_and_variante_fields'),
        ('ecommerce_persistence', '0020_resenaproductomodel_and_more'),
    ]

    operations = [
    ]
