# Generated by Django on 2026-02-15
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce_persistence', '0022_productodescuento_volumen'),
    ]

    operations = [
        migrations.AddField(
            model_name='productovariantemodel',
            name='cantidad_minima_mayorista',
            field=models.IntegerField(default=1, help_text='Cantidad minima para venta mayorista por variante'),
        ),
        migrations.CreateModel(
            name='ProductoVarianteDescuentoVolumenModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('cantidad_minima', models.IntegerField(default=1)),
                ('descuento_porcentaje', models.PositiveSmallIntegerField(default=0)),
                ('activo', models.BooleanField(default=True)),
                ('orden', models.IntegerField(default=0)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('variante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='descuentos_volumen', to='ecommerce_persistence.productovariantemodel')),
            ],
            options={
                'verbose_name': 'Descuento por Volumen (Variante)',
                'verbose_name_plural': 'Descuentos por Volumen (Variante)',
                'db_table': 'productos_variantes_descuentos_volumen',
                'ordering': ['cantidad_minima', 'orden'],
            },
        ),
        migrations.AddIndex(
            model_name='productovariantedescuentovolumenmodel',
            index=models.Index(fields=['variante', 'activo'], name='productos_v_variante_2de94b_idx'),
        ),
        migrations.AddIndex(
            model_name='productovariantedescuentovolumenmodel',
            index=models.Index(fields=['variante', 'cantidad_minima'], name='productos_v_variante_3148a1_idx'),
        ),
        migrations.AddConstraint(
            model_name='productovariantedescuentovolumenmodel',
            constraint=models.UniqueConstraint(fields=('variante', 'cantidad_minima'), name='unique_descuento_variante_por_cantidad'),
        ),
    ]
