# Generated by Django 6.0.1 on 2026-02-17 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce_persistence', '0024_add_estado_pago_envio'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='notificacionmodel',
            new_name='notificacio_usuario_cf1441_idx',
            old_name='notificacio_usuario__2a4eb6_idx',
        ),
        migrations.RenameIndex(
            model_name='notificacionmodel',
            new_name='notificacio_email_1699fa_idx',
            old_name='notificacio_email_78d0f0_idx',
        ),
        migrations.RenameIndex(
            model_name='notificacionmodel',
            new_name='notificacio_leida_008269_idx',
            old_name='notificacio_leida_81adf1_idx',
        ),
        migrations.RenameIndex(
            model_name='productodescuentovolumenmodel',
            new_name='productos_d_product_58b906_idx',
            old_name='productos_d_producto_3e0aa0_idx',
        ),
        migrations.RenameIndex(
            model_name='productodescuentovolumenmodel',
            new_name='productos_d_product_585dbc_idx',
            old_name='productos_d_producto_6b6c5f_idx',
        ),
        migrations.RenameIndex(
            model_name='productovariantedescuentovolumenmodel',
            new_name='productos_v_variant_2621f2_idx',
            old_name='productos_v_variante_2de94b_idx',
        ),
        migrations.RenameIndex(
            model_name='productovariantedescuentovolumenmodel',
            new_name='productos_v_variant_27649a_idx',
            old_name='productos_v_variante_3148a1_idx',
        ),
        migrations.RenameIndex(
            model_name='productovariantemodel',
            new_name='productos_v_product_8e477c_idx',
            old_name='productos_var_producto_4f2d5c_idx',
        ),
        migrations.RenameIndex(
            model_name='productovariantemodel',
            new_name='productos_v_product_f33e63_idx',
            old_name='productos_var_producto_6d4bc6_idx',
        ),
        migrations.RenameIndex(
            model_name='productovariantemodel',
            new_name='productos_v_product_d326ad_idx',
            old_name='productos_var_producto_1b6c50_idx',
        ),
        migrations.RenameIndex(
            model_name='productovariantemodel',
            new_name='productos_v_activo_a2fec1_idx',
            old_name='productos_var_activo_77e0b3_idx',
        ),
        migrations.AlterField(
            model_name='productomodel',
            name='largo',
            field=models.CharField(blank=True, choices=[('8', '8 pulgadas'), ('10', '10 pulgadas'), ('12', '12 pulgadas'), ('14', '14 pulgadas'), ('16', '16 pulgadas'), ('18', '18 pulgadas'), ('20', '20 pulgadas'), ('22', '22 pulgadas'), ('24', '24 pulgadas'), ('26', '26 pulgadas'), ('28', '28 pulgadas'), ('30', '30 pulgadas'), ('32', '32 pulgadas'), ('34', '34 pulgadas'), ('36', '36 pulgadas'), ('38', '38 pulgadas'), ('40', '40 pulgadas')], db_index=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='productovariantemodel',
            name='cantidad_minima_mayorista',
            field=models.IntegerField(default=1, help_text='Cantidad mínima para venta mayorista por variante'),
        ),
        migrations.AlterField(
            model_name='productovariantemodel',
            name='largo',
            field=models.CharField(blank=True, choices=[('8', '8 pulgadas'), ('10', '10 pulgadas'), ('12', '12 pulgadas'), ('14', '14 pulgadas'), ('16', '16 pulgadas'), ('18', '18 pulgadas'), ('20', '20 pulgadas'), ('22', '22 pulgadas'), ('24', '24 pulgadas'), ('26', '26 pulgadas'), ('28', '28 pulgadas'), ('30', '30 pulgadas'), ('32', '32 pulgadas'), ('34', '34 pulgadas'), ('36', '36 pulgadas'), ('38', '38 pulgadas'), ('40', '40 pulgadas')], db_index=True, max_length=50, null=True),
        ),
        migrations.AddIndex(
            model_name='ordenmodel',
            index=models.Index(fields=['estado_pago'], name='ordenes_estado__657c4b_idx'),
        ),
        migrations.AddIndex(
            model_name='ordenmodel',
            index=models.Index(fields=['estado_envio'], name='ordenes_estado__8d11e7_idx'),
        ),
    ]
