# Generated by Django 6.0.1 on 2026-02-17 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce_persistence', '0025_rename_notificacio_usuario__2a4eb6_idx_notificacio_usuario_cf1441_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordenmodel',
            name='guia_envio',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='ordenmodel',
            name='link_rastreo',
            field=models.URLField(blank=True, default='', max_length=600),
        ),
    ]
